# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MAKE.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1172, 904)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setIconSize(QtCore.QSize(50, 50))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(40, 40, 1091, 721))
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(870, 760, 291, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1172, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_2.setFont(font)
        self.menu_2.setObjectName("menu_2")
        self.menuzhibeizhihsu = QtWidgets.QMenu(self.menu_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menuzhibeizhihsu.setFont(font)
        self.menuzhibeizhihsu.setTabletTracking(False)
        self.menuzhibeizhihsu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menuzhibeizhihsu.setObjectName("menuzhibeizhihsu")
        self.menu_10 = QtWidgets.QMenu(self.menu_2)
        self.menu_10.setObjectName("menu_10")
        self.menu_11 = QtWidgets.QMenu(self.menu_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_11.setFont(font)
        self.menu_11.setObjectName("menu_11")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_3.setFont(font)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_4.setFont(font)
        self.menu_4.setObjectName("menu_4")
        self.menu_5 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_5.setFont(font)
        self.menu_5.setObjectName("menu_5")
        self.menu_7 = QtWidgets.QMenu(self.menu_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_7.setFont(font)
        self.menu_7.setObjectName("menu_7")
        self.menu_8 = QtWidgets.QMenu(self.menu_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_8.setFont(font)
        self.menu_8.setObjectName("menu_8")
        self.menu_9 = QtWidgets.QMenu(self.menu_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_9.setFont(font)
        self.menu_9.setObjectName("menu_9")
        self.menu_6 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.menu_6.setFont(font)
        self.menu_6.setObjectName("menu_6")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionNDVI = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionNDVI.setFont(font)
        self.actionNDVI.setObjectName("actionNDVI")
        self.actionSVM_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionSVM_2.setFont(font)
        self.actionSVM_2.setObjectName("actionSVM_2")
        self.actionBP_2 = QtWidgets.QAction(MainWindow)
        self.actionBP_2.setObjectName("actionBP_2")
        self.actionRF_2 = QtWidgets.QAction(MainWindow)
        self.actionRF_2.setObjectName("actionRF_2")
        self.actionSVM_3 = QtWidgets.QAction(MainWindow)
        self.actionSVM_3.setObjectName("actionSVM_3")
        self.actionBP_3 = QtWidgets.QAction(MainWindow)
        self.actionBP_3.setObjectName("actionBP_3")
        self.actionRF_3 = QtWidgets.QAction(MainWindow)
        self.actionRF_3.setObjectName("actionRF_3")
        self.actionSVM_4 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionSVM_4.setFont(font)
        self.actionSVM_4.setObjectName("actionSVM_4")
        self.actionBP_4 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionBP_4.setFont(font)
        self.actionBP_4.setObjectName("actionBP_4")
        self.actionRF_4 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionRF_4.setFont(font)
        self.actionRF_4.setObjectName("actionRF_4")
        self.actionNDBI = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionNDBI.setFont(font)
        self.actionNDBI.setObjectName("actionNDBI")
        self.actionsvi = QtWidgets.QAction(MainWindow)
        self.actionsvi.setObjectName("actionsvi")
        self.actionNDVI_2 = QtWidgets.QAction(MainWindow)
        self.actionNDVI_2.setObjectName("actionNDVI_2")
        self.action_NDVI = QtWidgets.QAction(MainWindow)
        self.action_NDVI.setObjectName("action_NDVI")
        self.actionNDVIre2_NDVI = QtWidgets.QAction(MainWindow)
        self.actionNDVIre2_NDVI.setObjectName("actionNDVIre2_NDVI")
        self.actionGNDVI = QtWidgets.QAction(MainWindow)
        self.actionGNDVI.setObjectName("actionGNDVI")
        self.actionVDWI = QtWidgets.QAction(MainWindow)
        self.actionVDWI.setObjectName("actionVDWI")
        self.actionMTCI = QtWidgets.QAction(MainWindow)
        self.actionMTCI.setObjectName("actionMTCI")
        self.actionGNDVI_2 = QtWidgets.QAction(MainWindow)
        self.actionGNDVI_2.setObjectName("actionGNDVI_2")
        self.actionSDVI = QtWidgets.QAction(MainWindow)
        self.actionSDVI.setObjectName("actionSDVI")
        self.actionREP = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.actionREP.setFont(font)
        self.actionREP.setObjectName("actionREP")
        self.menu.addAction(self.actionopen)
        self.menuzhibeizhihsu.addSeparator()
        self.menuzhibeizhihsu.addAction(self.actionsvi)
        self.menuzhibeizhihsu.addSeparator()
        self.menuzhibeizhihsu.addAction(self.actionNDVI_2)
        self.menuzhibeizhihsu.addSeparator()
        self.menuzhibeizhihsu.addAction(self.action_NDVI)
        self.menuzhibeizhihsu.addSeparator()
        self.menuzhibeizhihsu.addAction(self.actionNDVIre2_NDVI)
        self.menuzhibeizhihsu.addSeparator()
        self.menuzhibeizhihsu.addAction(self.actionVDWI)
        self.menuzhibeizhihsu.addSeparator()
        self.menuzhibeizhihsu.addAction(self.actionMTCI)
        self.menuzhibeizhihsu.addSeparator()
        self.menuzhibeizhihsu.addAction(self.actionGNDVI_2)
        self.menuzhibeizhihsu.addAction(self.actionSDVI)
        self.menuzhibeizhihsu.addSeparator()
        self.menu_10.addAction(self.actionNDBI)
        self.menu_11.addAction(self.actionREP)
        self.menu_2.addAction(self.menuzhibeizhihsu.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_10.menuAction())
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.menu_11.menuAction())
        self.menu_7.addAction(self.actionSVM_2)
        self.menu_7.addAction(self.actionBP_2)
        self.menu_7.addAction(self.actionRF_2)
        self.menu_8.addAction(self.actionSVM_3)
        self.menu_8.addAction(self.actionBP_3)
        self.menu_8.addAction(self.actionRF_3)
        self.menu_9.addAction(self.actionSVM_4)
        self.menu_9.addAction(self.actionBP_4)
        self.menu_9.addAction(self.actionRF_4)
        self.menu_5.addAction(self.menu_7.menuAction())
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.menu_8.menuAction())
        self.menu_5.addSeparator()
        self.menu_5.addAction(self.menu_9.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.menubar.addAction(self.menu_5.menuAction())
        self.menubar.addAction(self.menu_6.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "保存"))
        self.pushButton.setText(_translate("MainWindow", "退出"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "特征指数计算"))
        self.menuzhibeizhihsu.setTitle(_translate("MainWindow", "植被指数"))
        self.menu_10.setTitle(_translate("MainWindow", "建筑指数"))
        self.menu_11.setTitle(_translate("MainWindow", "自然指数"))
        self.menu_3.setTitle(_translate("MainWindow", "样本选取"))
        self.menu_4.setTitle(_translate("MainWindow", "特征选择"))
        self.menu_5.setTitle(_translate("MainWindow", "分类算法"))
        self.menu_7.setTitle(_translate("MainWindow", "十个波段"))
        self.menu_8.setTitle(_translate("MainWindow", "二十个波段"))
        self.menu_9.setTitle(_translate("MainWindow", "优选特征波段"))
        self.menu_6.setTitle(_translate("MainWindow", "制图"))
        self.actionopen.setText(_translate("MainWindow", "打开数据"))
        self.actionNDVI.setText(_translate("MainWindow", "NDVI"))
        self.actionNDVI.setToolTip(_translate("MainWindow", "NDVI"))
        self.actionSVM_2.setText(_translate("MainWindow", "SVM算法"))
        self.actionBP_2.setText(_translate("MainWindow", "BP算法"))
        self.actionRF_2.setText(_translate("MainWindow", "RF算法"))
        self.actionSVM_3.setText(_translate("MainWindow", "SVM算法"))
        self.actionBP_3.setText(_translate("MainWindow", "BP算法"))
        self.actionRF_3.setText(_translate("MainWindow", "RF算法"))
        self.actionSVM_4.setText(_translate("MainWindow", "SVM算法"))
        self.actionBP_4.setText(_translate("MainWindow", "BP算法"))
        self.actionRF_4.setText(_translate("MainWindow", "RF算法"))
        self.actionNDBI.setText(_translate("MainWindow", "NDBI(标准化差异建筑指数)"))
        self.actionsvi.setText(_translate("MainWindow", "SVI(土壤调整植被指数)"))
        self.actionNDVI_2.setText(_translate("MainWindow", "NDVI(归一化植被指数)"))
        self.action_NDVI.setText(_translate("MainWindow", "NDVIre1(红边NDVI)"))
        self.actionNDVIre2_NDVI.setText(_translate("MainWindow", "NDVIre2(红边NDVI)"))
        self.actionGNDVI.setText(_translate("MainWindow", "GNDVI(绿色标准化差异植被指数)"))
        self.actionVDWI.setText(_translate("MainWindow", "NDWI(归一化差异水指数)"))
        self.actionMTCI.setText(_translate("MainWindow", "MTCI(美国陆地叶绿素指数)"))
        self.actionGNDVI_2.setText(_translate("MainWindow", "GNDVI(绿色标准化差异植被指数)"))
        self.actionSDVI.setText(_translate("MainWindow", "SAVI(土壤调整植被指数)"))
        self.actionREP.setText(_translate("MainWindow", "REP(红边位置)"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()    # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_MainWindow()                    # ui是Ui_MainWindow()类的实例化对象
    ui.setupUi(MainWindow)                  # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
    MainWindow.show()                       # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())                   # 使用exit()或者点击关闭按钮退出QApplication